# Generated by Django 6.0.6 on 2026-06-17 02:04

import django.db.models.deletion
from django.db import migrations, models


def migrate_department_data(apps, schema_editor):
    Employee = apps.get_model('employees', 'Employee')
    Department = apps.get_model('employees', 'Department')

    for employee in Employee.objects.all():
        if not employee.department:
            continue

        department, _ = Department.objects.get_or_create(
            name=employee.department)
        employee.department_id = department.id
        employee.save(update_fields=['department'])


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='joining_date',
        ),
        migrations.RunPython(migrate_department_data,
                             migrations.RunPython.noop),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='employees.department'),
        ),
    ]
